### ISSUE TITLE
Drop down menu for entity selection

### ISSUE THREAD

**Issue by tonysprenk** [jonasbkarlsson/ev_smart_charging#120]
**Is your feature request related to a problem? Please describe.**
It’s annoying to have to search for the needed entities, copy them and paste them when setting up the integration. 
**Describe the solution you'd like**
Have the entity menus that need to be filled out be drop down menus of all the entities, yes it will be a long list but if it’s on alfabet it shouldn’t be too hard to find the right ones. 
**Describe alternatives you've considered**
Even better: have a search bar at the top but not sure if that’s possible, haven’t seen it before. .

**Comment by jonasbkarlsson** [comment]
Thanks for your suggestion.

However, since there is no possibility to have a search bar, I don't think it will be such a good idea for many people. You could have hundreds of entities making a drop down menu very long. So you more or less need to know the entity name in order to find it. When I search for entities in HA, I usually search for some known part in the middle of the name, or even the end of the entity name.

You only need to setup an instance of the integration once. So it's not that much time we are talking about.

And I also think it is better to search for entities in `Settings -> Devices & Services -> Entities` since you there can click on them and make sure that it is actually the correct one. This is not possible when configure an integration.
