### ISSUE TITLE
Recalculation

### ISSUE THREAD

**Issue by woopstar** [jonasbkarlsson/ev_smart_charging#128]
When SoC is lower than Target Soc, and you have disabled `Continuous charging` it needs to recalculate the charge schedule.

From the picture here, you see that time has passed the first charge point.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/2997782/218283367-bb1a4f43-3ea5-4341-86e9-2f0a58ab08ff.png">

**Comment by jonasbkarlsson** [comment]
Sorry for not replying to this sooner. I have priotities to fix a bug related to recalculation of the charge schedule. With the latest release [v1.7.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.7.0) there are a couple of changes in the logic for doing the recalculation. 

Maybe the issue you saw has been fixed.

I suggest that this issue is closed, and if you see this again with the v1.7.0, please report back!
