### ISSUE TITLE
hangs on "waiting for new prices"

### ISSUE THREAD

**Issue by Dominic-070** [jonasbkarlsson/ev_smart_charging#171]
probably due to negative prices tomorrow, it keeps saying "waiting for new prices"
![Screenshot_20230418_211640_Home Assistant](https://user-images.githubusercontent.com/62623885/232883995-a6670ee6-4d75-4c19-8e13-f6751b468325.jpg)
![Screenshot_20230418_211647_Home Assistant](https://user-images.githubusercontent.com/62623885/232884016-6968d370-3f2b-4366-acca-7177141a5132.jpg)

**Comment by jonasbkarlsson** [comment]
The reason for your issue is most likely that the price integration that you are using has not updated the prices for tomorrow. Notice that the attribute `Raw to days` does not contain tomorrow's prices. Unfortunately this happens sometimes. I have seen this issue with all three price integration that is supported. 

The easiest workaround is to reload the price integration. Settings -> Devices & Services -> Click on the three dots on your price integration -> Reload.

**Comment by Dominic-070** [comment]
Yes, thnx fixed.
See before and after.
![Uploading 20230418_214651.jpg…]()

**Comment by Dominic-070** [comment]
Force Nord Pole to reload
