### ISSUE TITLE
Calculation Process

### ISSUE THREAD

**Issue by adegenkolbe** [jonasbkarlsson/ev_smart_charging#280]
Hi,

this is not a feature request, nor is it a bug. I am just curious and want to understand how you calculate the duration for the charging.
I would assume that you need the charger speed and capacity of the battery to determine how long it will take to charge the car from the actual state of charge to the desired one. But as you don't have this information I don't know how you do it.

Thanks in advance and kind regards
Andy

**Comment by KentHage** [comment]
Because you set the "EV Smart Charging Charging speed" in the integration as how many percent you charge the car in an hour.

**Comment by jonasbkarlsson** [comment]
The explanation above is correct. It was a simple way to make the integration independent of absolute charging power and battery sizes. However, I have started to regret that choice. I might need to switch to charging power and battery size instead, in order to support more advanced functionality in the future.
