### ISSUE TITLE
Multiple cars using one charger

### ISSUE THREAD

**Issue by Xnygra** [jonasbkarlsson/ev_smart_charging#57]
Would it be possible to support two or more cars using one charger? In my case I have two EVs using the same home charger. A possible  solution would be during setup to add two (or more) cars and then to have a switch in the UI to switch between which car is connected, this switch can then be automated using the cars location, "charging port open", "cable connected" etc to automatically determine which car is connected.  

On a side note, thank you for this excellent integration, very good :)

**Comment by jonasbkarlsson** [comment]
The integration supports multiple instances, so you can have one EV Smart Charging per EV, and then with suitable automations activate the right instance.

For v1.2.0 you could control the `switch.ev_smart_charging_smart_charging_activated`.

However, there is soon coming a v1.3.0 that will have a `switch.ev_smart_charging_ev_connected` that would be even more suitable for this need.

**Comment by Strixx76** [comment]
I am using this integration with two cars that share on charger. Since both of my a cars are "dumb" (not connected to Home Assistant) I have made a input_select helper with two options. One for each car. Then I have made a automation in Node-RED that enables or disable the correct instance of this integration.

And it works like just perfect!
