### ISSUE TITLE
"Keep charger on" turns off charger if SOC dips below 100 after charge completion.

### ISSUE THREAD

**Issue by Skeletorjus** [jonasbkarlsson/ev_smart_charging#98]
## Version of the custom_component

Version 1.5.1

## Describe the bug
I have "Keep charger on" turned `on` to allow the EV to draw power from the house when warming up in the morning. This is after the EV has been fully charged.
The issue is that when the EV reports back that the climate control has been turned on, it also  (for whatever reason) returns a SOC of 98%. When this happens the integration turns off the charger which in turn makes the EV turn off the climate control. If the SOC is bumped back up to 100%, the charger is turned on again (but the EV remains cold 🥶).

**Comment by jonasbkarlsson** [comment]
I have looked into this, and I can see that this happens if the warming up is started (and the new SOC value is received) after the Charge completion time. But it doesn't happen if the new SOC value is received before the Charge completion time.

What value do you have for Charge completion time?

Did your issue happen after this time?

It shouldn't happen after the Charge completion time either, so this is a bug. But it would be good for me to get a confirmation on what happened.

**Comment by Skeletorjus** [comment]
You are correct. This happened around 06:30, after charge completion time, which was set to 06:00.

**Comment by jonasbkarlsson** [comment]
Should be fixed by #100.
Part of release [v1.5.2](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.5.2).

**Comment by jonasbkarlsson** [comment]
@Skeletorjus, thanks for reporting this. The implementation became much better now.

**Comment by Skeletorjus** [comment]
Good to hear, thanks a bunch for the quick fix!
